# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0003_auto_20160716_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
